/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as ReembolsoRouteImport } from './routes/reembolso'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AjudaIndexRouteImport } from './routes/ajuda.index'
import { Route as AjudaCategoriaIndexRouteImport } from './routes/ajuda.$categoria.index'
import { Route as AjudaCategoriaSlugRouteImport } from './routes/ajuda.$categoria.$slug'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const ReembolsoRoute = ReembolsoRouteImport.update({
  id: '/reembolso',
  path: '/reembolso',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaIndexRoute = AjudaIndexRouteImport.update({
  id: '/ajuda/',
  path: '/ajuda/',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaCategoriaIndexRoute = AjudaCategoriaIndexRouteImport.update({
  id: '/ajuda/$categoria/',
  path: '/ajuda/$categoria/',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaCategoriaSlugRoute = AjudaCategoriaSlugRouteImport.update({
  id: '/ajuda/$categoria/$slug',
  path: '/ajuda/$categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reembolso': typeof ReembolsoRoute
  '/termos': typeof TermosRoute
  '/ajuda/': typeof AjudaIndexRoute
  '/ajuda/$categoria/$slug': typeof AjudaCategoriaSlugRoute
  '/ajuda/$categoria/': typeof AjudaCategoriaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reembolso': typeof ReembolsoRoute
  '/termos': typeof TermosRoute
  '/ajuda': typeof AjudaIndexRoute
  '/ajuda/$categoria/$slug': typeof AjudaCategoriaSlugRoute
  '/ajuda/$categoria': typeof AjudaCategoriaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reembolso': typeof ReembolsoRoute
  '/termos': typeof TermosRoute
  '/ajuda/': typeof AjudaIndexRoute
  '/ajuda/$categoria/$slug': typeof AjudaCategoriaSlugRoute
  '/ajuda/$categoria/': typeof AjudaCategoriaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacidade'
    | '/reembolso'
    | '/termos'
    | '/ajuda/'
    | '/ajuda/$categoria/$slug'
    | '/ajuda/$categoria/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacidade'
    | '/reembolso'
    | '/termos'
    | '/ajuda'
    | '/ajuda/$categoria/$slug'
    | '/ajuda/$categoria'
  id:
    | '__root__'
    | '/'
    | '/privacidade'
    | '/reembolso'
    | '/termos'
    | '/ajuda/'
    | '/ajuda/$categoria/$slug'
    | '/ajuda/$categoria/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ReembolsoRoute: typeof ReembolsoRoute
  TermosRoute: typeof TermosRoute
  AjudaIndexRoute: typeof AjudaIndexRoute
  AjudaCategoriaSlugRoute: typeof AjudaCategoriaSlugRoute
  AjudaCategoriaIndexRoute: typeof AjudaCategoriaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reembolso': {
      id: '/reembolso'
      path: '/reembolso'
      fullPath: '/reembolso'
      preLoaderRoute: typeof ReembolsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda/': {
      id: '/ajuda/'
      path: '/ajuda'
      fullPath: '/ajuda/'
      preLoaderRoute: typeof AjudaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda/$categoria/': {
      id: '/ajuda/$categoria/'
      path: '/ajuda/$categoria'
      fullPath: '/ajuda/$categoria/'
      preLoaderRoute: typeof AjudaCategoriaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda/$categoria/$slug': {
      id: '/ajuda/$categoria/$slug'
      path: '/ajuda/$categoria/$slug'
      fullPath: '/ajuda/$categoria/$slug'
      preLoaderRoute: typeof AjudaCategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ReembolsoRoute: ReembolsoRoute,
  TermosRoute: TermosRoute,
  AjudaIndexRoute: AjudaIndexRoute,
  AjudaCategoriaSlugRoute: AjudaCategoriaSlugRoute,
  AjudaCategoriaIndexRoute: AjudaCategoriaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
